### ISSUE TITLE
retis does not build with rust 1.65

### ISSUE THREAD

**Issue by amorenoz** [retis-org/retis#138]
It yields the following error:

```
error[E0658]: custom discriminant values are not allowed in enums with tuple or struct variants
  --> src/core/filters/packets/ebpfinsn.rs:12:10
   |
11 |     Bpf(BpfJmpOp),
   |     ------------- tuple variant defined here
12 |     Ne = bpf_sys::BPF_JNE,
   |          ^^^^^^^^^^^^^^^^ disallowed custom discriminant
   |
   = note: see issue #60553 <https://github.com/rust-lang/rust/issues/60553> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `retis` due to previous error
root@823493a14136:/src# rustc --version
rustc 1.65.0 (897e37553 2022-11-02)
root@823493a14136:/src# 
```

Do we want to support it?
Note it's the one supported by latest Ubuntu LTS...

**Comment by vlrpl** [comment]
fixed with #139
